[tool.poetry]
name = "django-api-tools"
version = "0.1.0"
description = ""
authors = ["Orhan Hirsch <orhan.hirsch@oda.com>"]
readme = "README.md"
packages = [{include = "django_api_tools"}]

[tool.poetry.dependencies]
python = "^3.10"
Django = "^4.1.3"
pydantic = "^1.10.2"


[tool.poetry.group.dev.dependencies]
pytest = "^7.2.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
